### ISSUE TITLE
DEX: Deposit LP locks all pools, not just the pool you deposited into

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#227] opened 2021-05-05 18:38 UTC
When depositing into LP, only the pool you deposited into should be locked, not all LP positions. Currently, if you deposit into BALN / bnUSD, you can't withdraw from sICX / bnUSD

**Comment by gedanziger** [comment] 2021-06-14 19:55
This was likely due to user confusion, will close this unless it can be reproduced

**Closed by gedanziger** 2021-06-14 19:55 UTC
Labels: dex, p0
